config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'thoughts#index'
    resources :thoughts do
      resources :comments, only: :create
    end
    resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :thought

  validates :comment, presence: true
end

app/models/thought.rb
class Thought < ApplicationRecord
  belongs_to :user
  has_many :comments

  with_options presence: true do
    validates :title
    validates :content
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :thoughts
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @thought = Thought.find(params[:thought_id])
    @comment = @thought.comments.build(comment_params)
    if @comment.save
      redirect_to thought_path(@comment.thought)
    else
      render "thoughts/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, thought_id: params[:thought_id])
  end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  def index
    @thoughts = Thought.all
  end

  def new
    @thought = Thought.new
  end

  def create
    @thought = Thought.new(thought_params)
    if @thought.save
      redirect_to root_path
    else
      render action: :new
    end
  end

  def show
    @thought = Thought.find(params[:id])
    @comment = Comment.new
    @comments = @thought.comments.includes(:user)
  end

  def destroy
    thought = Thought.find(params[:id])
    if thought.destroy
       redirect_to root_path
    end
  end

  def edit
    @thought = Thought.find(params[:id])
  end

  def update
    thought = Thought.find(params[:id])
    if thought.update(thought_params)
      redirect_to root_path
    else
      render action: :update
    end
  end

private

  def thought_params
    params.require(:thought).permit( :title, :content).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @thoughts = @user.thoughts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThoughtApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><%= link_to "ThoughtApp", root_path, class: :logo %></h1>
            <div class="nav__right"> 
            <% if user_signed_in? %>
              <%= link_to "ログアウト", destroy_user_session_path, class: :nav__logout, method: :delete %>
              <%= link_to "新規投稿", new_thought_path, class: :nav__btn %>
            </div>
            <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
    <%= yield %>
  </body>
</html>

app/views/thoughts/_thought.html.erb
<div class="card__body">
    <%= link_to thought.title, thought_path(thought.id), class: :card__title%>
    
    <%= link_to "by#{thought.user.name}", user_path(thought.user), class: :card__user %>
</div>

app/views/thoughts/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @thought, local: true) do |f|%>
      <div class="field">
        <%= f.label :title, "タイトル" %><br />
        <%= f.text_field :title %>
      </div>

      <div class="field">
        <%= f.label :content, "内容" %><br />
        <%= f.text_area :content, class: :form__text %>
      </div>

      <div class="actions">
        <%= f.submit "保存する", class: :form__btn  %>
      </div>
    <% end %>
  </div>
</div>

app/views/thoughts/index.html.erb
<main class="main">
  <div class="inner">
      <% if user_signed_in? %>
      <div class="greeting">
        <%= "こんにちは," %>
        <%= link_to :"#{current_user.name}さん", user_path(current_user.id), class: :greeting__link%>
      </div>
      <% end %>
    <div class="card__wrapper">
      <%= render partial: "thought", collection: @thoughts %>
    </div>
  </div>
</main>

app/views/thoughts/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規投稿</h2>
        <%= form_with(model: @thought, local: true) do |f|%>
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content, "内容" %><br />
    <%= f.text_area :content, class: :form__text %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>
    </div>
  </div>
</div>

app/views/thoughts/show.html.erb
<main class="main">
  <div class="inner">
    <div class="thought_wrapper">
      <p class="thought_hedding">
        <%= @thought.title %>
      </p>
      <%= link_to "#{@thought.user.name}の考察", user_path(@thought.user_id), class: :thought__user %>
      <% if user_signed_in? && current_user.id == @thought.user_id%>
        <div class="thought_manage">
          <%= link_to "編集する", edit_thought_path, class: :thought__btn %>
          <%= link_to "削除する", thought_path, class: :thought__btn, method: :delete %>
        </div>
        <% end %>
        <div class="thought__comments">
        <% if user_signed_in? %>
          <%= form_with(model: [ @thought, @comment], local: true) do |f|%>
            <div class="field">
              <%= f.label :comment, "コメント" %><br />
              <%= f.text_field :comment %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn %>
            </div>
          <% end %> 
        <% end %>
        <ul class="comments_lists">
           <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.comment %>
              <%= link_to comment.user.name, user_path(comment.user_id), class: :comment_user %>
            </li>
            <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんのThoughts" %>
      </h2>
      <div class="user__card">
        <%= render partial: "thoughts/thought", collection: @thoughts %>
      </div>
    </div>
  </div>
</div>